import Head from 'next/head'
// use inter.className
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import AppHeader from '../../components/appHeader'
import MuiBreadcrumb from '../../components/Breadcrumb'
import Content from '../../components/Content'
import Faq from '../../components/FAQ'
import AppFooter from '../../components/appFooter'

export default function Home() {
  return (
    <>
      <Head>
        <title>How It Works</title>
        <meta name="description" content="Generated by Shahin" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        
        <AppHeader/>
        
        <MuiBreadcrumb />

        {/* content */}
        <Content/>

        <Faq />

        <AppFooter/>
        
      </main>
    </>
  )
}
