import Head from 'next/head'
// use inter.className
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import AppHeader from '../../components/appHeader'
import MuiBreadcrumb from '../../components/Breadcrumb'
import Content from '../../components/Content'
import Faq from '../../components/FAQ'
import AppFooter from '../../components/appFooter'

export default function Home() {
  return (
    <>
      <Head>
        <title>How It Works</title>
        <meta name="description" content="Generated by Shahin" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-sign.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@300;400&family=DM+Sans:opsz@9..40&display=swap" rel="stylesheet"/>
      </Head>
      <main className={inter.className}>
        
        <AppHeader/>
        
        <MuiBreadcrumb />

        {/* content */}
        <Content/>

        <Faq />

        <AppFooter/>
        
      </main>
    </>
  )
}
